theme: jekyll-theme-leap-day
markdown: kramdown
title: 福来鸽
description: 半吊子程序猿-立flag好手-间歇性拼搏者
encoding: UTF-8
rss: true
deploy:
  type: git
  # 这里填写博客 repo 地址，非源码地址
  repo: git@github.com:flaging/flaging.git

